### ISSUE TITLE
NoSuchMethodException on invalidateRAM

### ISSUE THREAD

**Issue by piandrus** [vincentbrison/dualcache#28]
Hi,

When running unit tests with RobolectricGradleTestRunner I get a NoSuchMethodException exception stack trace when invalidating cache:

```
java.lang.NoSuchMethodException: java.util.LinkedHashMap.eldest()
	at java.lang.Class.getMethod(Class.java:1786)
	at com.vincentbrison.openlibraries.android.dualcache.RamLruCache.trimToSize(RamLruCache.java:210)
	at com.vincentbrison.openlibraries.android.dualcache.ReferenceLruCache.trimToSize(ReferenceLruCache.java:7)
	at com.vincentbrison.openlibraries.android.dualcache.RamLruCache.evictAll(RamLruCache.java:316)
	at com.vincentbrison.openlibraries.android.dualcache.DualCache.invalidateRAM(DualCache.java:415)
	at com.vincentbrison.openlibraries.android.dualcache.DualCache.invalidate(DualCache.java:407)
```

I guess this is due to difference between Oracle and Dalvik implementation. Maybe an iterator mechanism could be used when calling "eldest()" fails? This could make unit tests outside Android environment work better. What do you think?

Thanks for working on this library! :)

**Comment by vincentbrison** [comment]
Hi,

Thanks for your feedback.

The library is not made of pur java code. If it was the case, I would wrote unit tests which could be run on regular Java VMs. But this is not the case, the library include Android specific code, and thus the instrumentation tests I wrote are made to be run on regular Android devices. Genymotion and official emulators are supported.
